services:
  postgres_challenge_1:
    image: pgvector/pgvector:pg17
    container_name: postgres-vector-challenge-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - langchain-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bootstrap_vector_ext_challenge_1:
    image: pgvector/pgvector:pg17
    depends_on:
      postgres_challenge_1:
        condition: service_healthy
    command: >
      PGPASSWORD=postgres
      psql -h postgres -U postgres -d rag -c "CREATE EXTENSION IF NOT EXISTS vector;"
    networks:
      - langchain-network
    restart: "no"

volumes:
  pgdata:

networks:
  langchain-network:
    driver: bridge